name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poppler
        run: sudo apt-get install poppler-utils

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Lint with ruff
        run: ruff check --fix --exit-non-zero-on-fix .

      - name: Run tests
        run: make test